function exportAndCrop(fileName)

export_fig(sprintf(fileName), ...
    "-r600", ...
    "-painters", ...
    "-q101", ...
    "-a4", ...
    "-nocrop");
close all;
removeVerticalWhitespace(fileName);

end