function prettyTextArrow(x, y, str)

pos = sym(gca().Position);
xLim = sym(gca().XLim);
yLim = sym(gca().YLim);

X = ((x - xLim(1)) / (xLim(2) - xLim(1)) * pos(3)) + pos(1);
Y = ((y - yLim(1)) / (yLim(2) - yLim(1)) * pos(4)) + pos(2);
annotation('textarrow', 'Units', 'Points', 'X', X, 'Y', Y, ...
    'String', str, ...
    'Interpreter', 'Latex', ...
    'HorizontalAlignment', 'Center', ...
    'VerticalAlignment', 'Middle', ...
    'HeadLength', 5, ...
    'HeadWidth', 5);

end